### ISSUE TITLE
While using your product, I found that it cannot be used normally in China

### ISSUE THREAD

**Issue by wuliao6688** [Smartproxy/Smartproxy#10]
If your agent product is used in China, it is not abnormal. It needs an agent manager to transfer through a server and then to your server. For example, Luminati provides such a software, https://luminati-china .biz/products/proxy-manager, do you have anything similar?

I also used the domain name china-gate.dc.visitxiangtan.com, but it still cannot be resolved

**Comment by 4ofour** [comment]
Hey! With recent updates it should work normally. If you are still having issues feel free to hop into our chat and we will help you out there: https://direct.lc.chat/12092754/1
