### ISSUE TITLE
Connection issue - python 

### ISSUE THREAD

**Issue by PalasOnGithub** [Smartproxy/Smartproxy#13]
Hi I have bought Mobile residential proxies and I can't connect them using telethon lib
I'm facing timeout errors whenever I try

Check list: 
1. I'm sure the issue doesn't come from my side 
2. I'm sure I choose proxy from uncensored areas 
3. I'm sure I'm connecting in right way!

My code is pretty simple as well:
`def get_proxy() -> dict:
with open("proxies.txt", "r") as f:
proxy = random.choice([line.split(':') for line in f])
print(proxy)
return {
'proxy_type': python_socks.ProxyType.HTTP, # (mandatory) protocol to use (see above)
'addr': str(proxy[2]), # (mandatory) proxy IP address
'port': int(proxy[3].replace('\n', '')), # (mandatory) proxy port number
'username': str(proxy[0]), # (optional) username if the proxy requires auth
'password': str(proxy[1]), # (optional) password if the proxy requires auth
'rdns': True # (optional) whether to use remote or local resolve, default remote
}`

And I just put it in Telegramclient of telethon but timeout issues

**Comment by 4ofour** [comment]
Hey! Please come chat with us via Livechat and we can quickly troubleshoot your issue with Telegram and mobile proxies: https://direct.lc.chat/12092754/1
